### Main api
GET http://localhost:8000/localhost:8000/api/v1/admin-user

### post new admin user
POST  http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
     "fName": "Subin",
    "lName": "Basnet",
    "email": "subin@basnet10101011.com",
    "password": "subin",
    "phone": "98098098098",
    "address": "sydney",
    "dob": "2020-12-12"
}
### login admin user
POST  http://localhost:8000/api/v1/admin-user/login
Content-Type: application/json

{
    "email": "dibby@10.com",
    "password": "12"
  
}
 ###  =========================  ###


### Insert Category
POST  http://localhost:8000/api/v1/category
Content-Type: application/json

{
   "status": "active",
    "name": "Window",
    "parentId": "6483cc10290d801699d14f45"
  
}

### Get category
GET http://localhost:8000/api/v1/category

### 
GET  http://localhost:8000/api/v1/admin-user/accessJwt
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRpYmJ5QDEwLmNvbSIsImlhdCI6MTY4NjU0MzY3NywiZXhwIjoxNjg5MTM1Njc3fQ.IaRhuDJ6jTRJ_WcaG2zfN3_cqK05Xq16UV6tG0fwk2k