### Main api
GET http://localhost:8000/localhost:8000/api/v1/admin-user

### post new admin user
POST  http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
     "fName": "Subin",
    "lName": "Basnet",
    "email": "subin@basnet10101011.com",
    "password": "subin",
    "phone": "98098098098",
    "address": "sydney",
    "dob": "2020-12-12"
}
### login admin user
POST  http://localhost:8000/api/v1/admin-user/login
Content-Type: application/json

{
    "email": "dibby@10.com",
    "password": "12"
  
}

### request otp for passwored reset
POST http://localhost:8000/api/v1/admin-user/request-password-reset-otp
Content-Type: application/json

{
"email": "sumina@4.com"
}

 ###  =========================  ###


### Insert Category
POST  http://localhost:8000/api/v1/category
Content-Type: application/json

{
   "status": "active",
    "name": "Window",
    "parentId": ""
  
}

### Get category
GET http://localhost:8000/api/v1/category

### 
GET  http://localhost:8000/api/v1/admin-user/accessJwt
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRpYmJ5QDEwLmNvbSIsImlhdCI6MTY4NjU0MzY3NywiZXhwIjoxNjg5MTM1Njc3fQ.IaRhuDJ6jTRJ_WcaG2zfN3_cqK05Xq16UV6tG0fwk2k


### ==========payment Method =========###
### GET
GET http://localhost:8000/api/v1/payment-method

### POST
POST http://localhost:8000/api/v1/payment-method
Content-Type: application/json

{
    "status": "inactive",
    "name": "Pay by credit card",
    "description": "Follow the instruction to pay by credit card, AMEX not support"
}

### UPDATE
PUT http://localhost:8000/api/v1/payment-method
Content-Type: application/json

{
    "_id": "6487c1fc2a90a5b97b22de01",
    "status": "active",
    "name": "Pay by credit card ",
    "description": "Follow the instruction to pay by credit card"
}
### Delete
DELETE  http://localhost:8000/api/v1/payment-method/6487c1fc2a90a5b97b22de01

### =======products api==========#
### Get products
GET  http://localhost:8000/api/v1/product

### Post products
POST  http://localhost:8000/api/v1/product
Content-Type: application/json

{
    "name": "Mac book pro",
    "status": "inactive",
    "sku": "c-14",
    "description": "This is best selling laptop",
    "quantity": 100,
    "price": 3000,
    "salesPrice": 0,
    "salesStartDate": null,
    "salesEndDate": null,
    "catId": "6305666feb7e2d255da263f6"
}

#=============order api ========#
### get orders
GET http://localhost:8000/api/v1/order/11